# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e54826e748e802cc152b25bcbfe8c7c2dfe18218913690bdbd7ea88b3ff1c8dc1d013c725570cbacc69c61e63994ec4351ba5fb84ac5368d48cc35214284dc4e

test:
  secret_key_base: afccfbcc5f703f04a0a539bea846f1e70215b924f9f7494d631980c7f84d19b00cbfc0a98b5236e776ade0ac2533f3704cd887057f146cfc612ccbece883b70c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
